{
  "openapi": "3.0.1",
  "info": {
    "title": "IVT API",
    "version": "v1"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Local"
    },
    {
      "url": "https://developmentapi.ienterprise.info/network",
      "description": "Dev"
    },
    {
      "url": "https://stagingapi.ienterprise.com/network",
      "description": "Staging"
    }
  ],
  "paths": {
    "/config": {
      "get": {
        "tags": [
          "config-api"
        ],
        "summary": "Returns configuration configured in environment",
        "operationId": "getConfig",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseString"
                }
              }
            }
          },
          "401": {
            "description": "Returns unauthorized/forbidden response code"
          },
          "500": {
            "description": "returns error response(success=false,body=null) with messageCodes",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "messageCodes": [
                    "unknown.error"
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ApiResponseString": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "messageCodes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "body": {
            "type": "string"
          }
        }
      }
    }
  }
}
